"""phase1 data-analysis models

Revision ID: d846a1ecafa8
Revises: 0001
Create Date: 2026-07-03 12:21:43.388135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd846a1ecafa8'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_steps',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('query_id', sa.Text(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_profiles',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('dataset_id', sa.Text(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('source_format', sa.Text(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('col_count', sa.Integer(), nullable=False),
    sa.Column('masked_sample', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queries',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('dataset_ids', sa.JSON(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('clarifying_question', sa.Text(), nullable=True),
    sa.Column('chart_spec', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queries')
    op.drop_table('datasets')
    op.drop_table('dataset_profiles')
    op.drop_table('analysis_steps')
    # ### end Alembic commands ###
